// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDasHbVMnmJugOs_HCHCchbhVbsiHwxo2A',
    appId: '1:4835423999:web:9e78af8bdc77f6cd6cfeca',
    messagingSenderId: '4835423999',
    projectId: 'futdle-vitor',
    authDomain: 'futdle-vitor.firebaseapp.com',
    storageBucket: 'futdle-vitor.firebasestorage.app',
    measurementId: 'G-Y8Y3YMLJER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4n3D1O5cfBYstIg-5fsCXxlAP0Mn2xjc',
    appId: '1:4835423999:android:d68376f95eec53de6cfeca',
    messagingSenderId: '4835423999',
    projectId: 'futdle-vitor',
    storageBucket: 'futdle-vitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEH7C3-R_9YgIv5rsfFKl0VgncFmC1R9E',
    appId: '1:4835423999:ios:aa2e54114ead79636cfeca',
    messagingSenderId: '4835423999',
    projectId: 'futdle-vitor',
    storageBucket: 'futdle-vitor.firebasestorage.app',
    iosBundleId: 'com.example.futdle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEH7C3-R_9YgIv5rsfFKl0VgncFmC1R9E',
    appId: '1:4835423999:ios:aa2e54114ead79636cfeca',
    messagingSenderId: '4835423999',
    projectId: 'futdle-vitor',
    storageBucket: 'futdle-vitor.firebasestorage.app',
    iosBundleId: 'com.example.futdle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDasHbVMnmJugOs_HCHCchbhVbsiHwxo2A',
    appId: '1:4835423999:web:2c00d06a4a015e0b6cfeca',
    messagingSenderId: '4835423999',
    projectId: 'futdle-vitor',
    authDomain: 'futdle-vitor.firebaseapp.com',
    storageBucket: 'futdle-vitor.firebasestorage.app',
    measurementId: 'G-8RNN7TQ3JP',
  );
}
